### ISSUE TITLE
Cannot find module './db.json'

### ISSUE THREAD

**Issue by Neats29** [jshttp/mime-db#80] opened 2017-06-12 15:31 UTC
I'm getting this error and no matter what I do I can't get rid of it.

I'm using typescript v2.3.4
node v7.8.0 (though seeing the same issue with 7.4.0)
and my tsconfig is:
 ```
{
  "compilerOptions": {
    "alwaysStrict": true,
    "outDir": "built",
    "lib": [ "es6" ],
		"module": "commonjs",
		"target": "es6",
    "pretty": true,
    "removeComments": true,
		"sourceMap": true
  },
  "include": [
      "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
I've ran `npm cache clean` and re-installed all my node modules. 
If I delete my generated built folder and run the code, everything works as expected but when I run it again, I get the above error. Any ideas?

**Comment by dougwilson** [comment] 2017-06-15 01:16
Hi @Neats29 I'm not very familiar with TypeScript, so I don't know what that JSON means. Is it possible you can provide the exact instructions of what I need to do to reproduce the issue so I can take a look? Perhaps a git repo I can just clone and then run a command in to see it?

**Comment by dougwilson** [comment] 2017-07-11 02:09
Closing since I never heard back.

**Closed by dougwilson** 2017-07-11 02:09 UTC
Labels: awaiting more info
