### ISSUE TITLE
Compressible for image/svg+xml?

### ISSUE THREAD

**Issue by danny0838** [jshttp/mime-db#113] opened 2017-12-29 16:31 UTC
This seems to a tricky issue.

Mime type image/svg+xml has svg and svgz listed, and is marked compressible.

svg is plain text is expectedly compressible. However, svgz is already zip compressed format and should be not compressible.

**Comment by dougwilson** [comment] 2017-12-29 16:31
Duplicate of #110

**Closed by dougwilson** 2017-12-29 16:31 UTC
